markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: mrxin321
author: "蔡祖鑫"
email: mrxin321#163.com
name: "蔡祖鑫个人博客"
url: https://github.com/mrxin321
domain: mrxin321.github.io
all_categories: [
["read", "读书笔记","/posts/read.html"], 
["unity", "unity学习","/posts/program.html"],
["daily", "每日回顾","/other.html"]
["other", "其他","/posts/other.html"],
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
