markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: mrxin321
author: "蔡祖鑫"
email: mrxin321#163.com
name: "蔡祖鑫个人博客"
url: http://mrxin321.github.io
domain: mrxin321.github.io
all_categories: [
["android", "unity学习","/posts/android.html"], 
["program", "软件编程","/posts/program.html"],
["web", "每日回顾","/posts/web.html"], 
["linux", "游戏","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
